[2023-01-10T01:50:26.563179+01:00] default.ERROR: Code 0: An exception occurred in the driver: could not find driver in /__app__/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91 [] {"url":"/admin/sign/in?backlink=4wrl9","ip":"172.18.0.1","http_method":"POST","server":"localhost","referrer":"http://localhost:1234/admin/sign/in?backlink=4wrl9","file":"/__app__/vendor/tracy/tracy/src/Bridges/Psr/PsrToTracyLoggerAdapter.php","line":57,"class":"Tracy\\Bridges\\Psr\\PsrToTracyLoggerAdapter","callType":"->","function":"log","memory_peak_usage":"4 MB","process_id":2889}
[2023-01-10T01:50:26.571638+01:00] default.ERROR: Doctrine\DBAL\Exception\DriverException: An exception occurred in the driver: could not find driver in /__app__/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /__app__/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /__app__/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:30)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /__app__/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} {"url":"/admin/sign/in?backlink=4wrl9","ip":"172.18.0.1","http_method":"POST","server":"localhost","referrer":"http://localhost:1234/admin/sign/in?backlink=4wrl9","file":"/__app__/vendor/tracy/tracy/src/Bridges/Psr/PsrToTracyLoggerAdapter.php","line":57,"class":"Tracy\\Bridges\\Psr\\PsrToTracyLoggerAdapter","callType":"->","function":"log","memory_peak_usage":"4 MB","process_id":2889}
[2023-01-10T02:03:10.162064+01:00] default.ERROR: Code 0: An exception occurred in the driver: could not find driver in /__app__/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91 [] {"url":"/admin/sign/in?backlink=4wrl9","ip":"172.18.0.1","http_method":"POST","server":"localhost","referrer":"http://localhost:1234/admin/sign/in?backlink=4wrl9","file":"/__app__/vendor/tracy/tracy/src/Bridges/Psr/PsrToTracyLoggerAdapter.php","line":57,"class":"Tracy\\Bridges\\Psr\\PsrToTracyLoggerAdapter","callType":"->","function":"log","memory_peak_usage":"4 MB","process_id":2894}
[2023-01-10T02:03:10.162505+01:00] default.ERROR: Doctrine\DBAL\Exception\DriverException: An exception occurred in the driver: could not find driver in /__app__/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /__app__/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /__app__/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:30)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /__app__/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} {"url":"/admin/sign/in?backlink=4wrl9","ip":"172.18.0.1","http_method":"POST","server":"localhost","referrer":"http://localhost:1234/admin/sign/in?backlink=4wrl9","file":"/__app__/vendor/tracy/tracy/src/Bridges/Psr/PsrToTracyLoggerAdapter.php","line":57,"class":"Tracy\\Bridges\\Psr\\PsrToTracyLoggerAdapter","callType":"->","function":"log","memory_peak_usage":"4 MB","process_id":2894}
[2023-01-10T02:03:21.639252+01:00] default.ERROR: Code 0: An exception occurred in the driver: could not find driver in /__app__/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91 [] {"url":"/admin/sign/in?backlink=qo62l","ip":"172.18.0.1","http_method":"POST","server":"localhost","referrer":"http://localhost:1234/admin/sign/in?backlink=qo62l","file":"/__app__/vendor/tracy/tracy/src/Bridges/Psr/PsrToTracyLoggerAdapter.php","line":57,"class":"Tracy\\Bridges\\Psr\\PsrToTracyLoggerAdapter","callType":"->","function":"log","memory_peak_usage":"4 MB","process_id":2893}
[2023-01-10T02:03:21.639548+01:00] default.ERROR: Doctrine\DBAL\Exception\DriverException: An exception occurred in the driver: could not find driver in /__app__/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /__app__/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /__app__/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:30)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /__app__/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} {"url":"/admin/sign/in?backlink=qo62l","ip":"172.18.0.1","http_method":"POST","server":"localhost","referrer":"http://localhost:1234/admin/sign/in?backlink=qo62l","file":"/__app__/vendor/tracy/tracy/src/Bridges/Psr/PsrToTracyLoggerAdapter.php","line":57,"class":"Tracy\\Bridges\\Psr\\PsrToTracyLoggerAdapter","callType":"->","function":"log","memory_peak_usage":"4 MB","process_id":2893}
[2023-01-10T02:36:07.175506+01:00] default.ERROR: Code 0: An exception occurred in the driver: could not find driver in /__app__/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91 [] {"url":"/admin/sign/in?backlink=qo62l","ip":"172.18.0.1","http_method":"POST","server":"localhost","referrer":"http://localhost:1234/admin/sign/in?backlink=qo62l","file":"/__app__/vendor/tracy/tracy/src/Bridges/Psr/PsrToTracyLoggerAdapter.php","line":57,"class":"Tracy\\Bridges\\Psr\\PsrToTracyLoggerAdapter","callType":"->","function":"log","memory_peak_usage":"4 MB","process_id":2889}
[2023-01-10T02:36:07.176305+01:00] default.ERROR: Doctrine\DBAL\Exception\DriverException: An exception occurred in the driver: could not find driver in /__app__/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /__app__/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /__app__/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:30)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /__app__/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} {"url":"/admin/sign/in?backlink=qo62l","ip":"172.18.0.1","http_method":"POST","server":"localhost","referrer":"http://localhost:1234/admin/sign/in?backlink=qo62l","file":"/__app__/vendor/tracy/tracy/src/Bridges/Psr/PsrToTracyLoggerAdapter.php","line":57,"class":"Tracy\\Bridges\\Psr\\PsrToTracyLoggerAdapter","callType":"->","function":"log","memory_peak_usage":"4 MB","process_id":2889}
[2023-01-10T03:07:04.308248+01:00] default.ERROR: Code 0: An exception occurred in the driver: could not find driver in /__app__/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91 [] {"url":"/admin/sign/in?backlink=qo62l","ip":"172.18.0.1","http_method":"POST","server":"localhost","referrer":"http://localhost:1234/admin/sign/in?backlink=qo62l","file":"/__app__/vendor/tracy/tracy/src/Bridges/Psr/PsrToTracyLoggerAdapter.php","line":57,"class":"Tracy\\Bridges\\Psr\\PsrToTracyLoggerAdapter","callType":"->","function":"log","memory_peak_usage":"4 MB","process_id":2890}
[2023-01-10T03:07:04.308502+01:00] default.ERROR: Doctrine\DBAL\Exception\DriverException: An exception occurred in the driver: could not find driver in /__app__/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /__app__/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /__app__/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:30)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /__app__/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} {"url":"/admin/sign/in?backlink=qo62l","ip":"172.18.0.1","http_method":"POST","server":"localhost","referrer":"http://localhost:1234/admin/sign/in?backlink=qo62l","file":"/__app__/vendor/tracy/tracy/src/Bridges/Psr/PsrToTracyLoggerAdapter.php","line":57,"class":"Tracy\\Bridges\\Psr\\PsrToTracyLoggerAdapter","callType":"->","function":"log","memory_peak_usage":"4 MB","process_id":2890}
[2023-01-10T03:07:24.933209+01:00] default.ERROR: Code 0: An exception occurred in the driver: could not find driver in /__app__/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91 [] {"url":"/admin/sign/in?backlink=unlf2","ip":"172.18.0.1","http_method":"POST","server":"localhost","referrer":"http://localhost:1234/admin/sign/in?backlink=unlf2","file":"/__app__/vendor/tracy/tracy/src/Bridges/Psr/PsrToTracyLoggerAdapter.php","line":57,"class":"Tracy\\Bridges\\Psr\\PsrToTracyLoggerAdapter","callType":"->","function":"log","memory_peak_usage":"4 MB","process_id":2892}
[2023-01-10T03:07:24.933396+01:00] default.ERROR: Doctrine\DBAL\Exception\DriverException: An exception occurred in the driver: could not find driver in /__app__/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /__app__/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /__app__/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:30)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /__app__/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} {"url":"/admin/sign/in?backlink=unlf2","ip":"172.18.0.1","http_method":"POST","server":"localhost","referrer":"http://localhost:1234/admin/sign/in?backlink=unlf2","file":"/__app__/vendor/tracy/tracy/src/Bridges/Psr/PsrToTracyLoggerAdapter.php","line":57,"class":"Tracy\\Bridges\\Psr\\PsrToTracyLoggerAdapter","callType":"->","function":"log","memory_peak_usage":"4 MB","process_id":2892}
[2023-01-10T03:28:47.696022+01:00] default.ERROR: Code 0: An exception occurred in the driver: could not find driver in /__app__/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91 [] {"url":"/admin/sign/in?backlink=unlf2","ip":"172.18.0.1","http_method":"POST","server":"localhost","referrer":"http://localhost:1234/admin/sign/in?backlink=unlf2","file":"/__app__/vendor/tracy/tracy/src/Bridges/Psr/PsrToTracyLoggerAdapter.php","line":57,"class":"Tracy\\Bridges\\Psr\\PsrToTracyLoggerAdapter","callType":"->","function":"log","memory_peak_usage":"4 MB","process_id":2893}
[2023-01-10T03:28:47.696345+01:00] default.ERROR: Doctrine\DBAL\Exception\DriverException: An exception occurred in the driver: could not find driver in /__app__/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /__app__/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /__app__/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:30)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /__app__/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} {"url":"/admin/sign/in?backlink=unlf2","ip":"172.18.0.1","http_method":"POST","server":"localhost","referrer":"http://localhost:1234/admin/sign/in?backlink=unlf2","file":"/__app__/vendor/tracy/tracy/src/Bridges/Psr/PsrToTracyLoggerAdapter.php","line":57,"class":"Tracy\\Bridges\\Psr\\PsrToTracyLoggerAdapter","callType":"->","function":"log","memory_peak_usage":"4 MB","process_id":2893}
[2023-01-10T03:28:59.466016+01:00] default.ERROR: Code 0: An exception occurred in the driver: could not find driver in /__app__/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91 [] {"url":"/admin/sign/in?backlink=4nqnp","ip":"172.18.0.1","http_method":"POST","server":"localhost","referrer":"http://localhost:1234/admin/sign/in?backlink=4nqnp","file":"/__app__/vendor/tracy/tracy/src/Bridges/Psr/PsrToTracyLoggerAdapter.php","line":57,"class":"Tracy\\Bridges\\Psr\\PsrToTracyLoggerAdapter","callType":"->","function":"log","memory_peak_usage":"4 MB","process_id":2889}
[2023-01-10T03:28:59.466344+01:00] default.ERROR: Doctrine\DBAL\Exception\DriverException: An exception occurred in the driver: could not find driver in /__app__/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /__app__/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /__app__/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:30)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /__app__/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} {"url":"/admin/sign/in?backlink=4nqnp","ip":"172.18.0.1","http_method":"POST","server":"localhost","referrer":"http://localhost:1234/admin/sign/in?backlink=4nqnp","file":"/__app__/vendor/tracy/tracy/src/Bridges/Psr/PsrToTracyLoggerAdapter.php","line":57,"class":"Tracy\\Bridges\\Psr\\PsrToTracyLoggerAdapter","callType":"->","function":"log","memory_peak_usage":"4 MB","process_id":2889}
[2023-01-10T03:29:57.945883+01:00] default.ERROR: Code 2002: An exception occurred in the driver: php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution in /__app__/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:103 [] {"url":"/admin/sign/in?backlink=4nqnp","ip":"172.18.0.1","http_method":"POST","server":"localhost","referrer":"http://localhost:1234/admin/sign/in?backlink=4nqnp","file":"/__app__/vendor/tracy/tracy/src/Bridges/Psr/PsrToTracyLoggerAdapter.php","line":57,"class":"Tracy\\Bridges\\Psr\\PsrToTracyLoggerAdapter","callType":"->","function":"log","memory_peak_usage":"10 MB","process_id":2888}
[2023-01-10T03:29:57.946161+01:00] default.ERROR: Doctrine\DBAL\Exception\ConnectionException: An exception occurred in the driver: php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution #2002 in /__app__/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:103 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 2002): An exception occurred in the driver: php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /__app__/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:103)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\Mysqli\\Exception\\ConnectionFailed(code: 2002): php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /__app__/vendor/doctrine/dbal/src/Driver/Mysqli/Exception/ConnectionFailed.php:26)"} {"url":"/admin/sign/in?backlink=4nqnp","ip":"172.18.0.1","http_method":"POST","server":"localhost","referrer":"http://localhost:1234/admin/sign/in?backlink=4nqnp","file":"/__app__/vendor/tracy/tracy/src/Bridges/Psr/PsrToTracyLoggerAdapter.php","line":57,"class":"Tracy\\Bridges\\Psr\\PsrToTracyLoggerAdapter","callType":"->","function":"log","memory_peak_usage":"10 MB","process_id":2888}
[2023-01-10T03:31:14.625967+01:00] default.ERROR: Doctrine\DBAL\Exception: The given 'driver' mysql is unknown, Doctrine currently supports only the following drivers: pdo_mysql, pdo_sqlite, pdo_pgsql, pdo_oci, oci8, ibm_db2, pdo_sqlsrv, mysqli, sqlsrv in /__app__/vendor/doctrine/dbal/src/Exception.php:91 {"exception":"[object] (Doctrine\\DBAL\\Exception(code: 0): The given 'driver' mysql is unknown, Doctrine currently supports only the following drivers: pdo_mysql, pdo_sqlite, pdo_pgsql, pdo_oci, oci8, ibm_db2, pdo_sqlsrv, mysqli, sqlsrv at /__app__/vendor/doctrine/dbal/src/Exception.php:91)"} {"url":"/admin/sign/in?backlink=4nqnp","ip":"172.18.0.1","http_method":"POST","server":"localhost","referrer":"http://localhost:1234/admin/sign/in?backlink=4nqnp","file":"/__app__/vendor/tracy/tracy/src/Bridges/Psr/PsrToTracyLoggerAdapter.php","line":57,"class":"Tracy\\Bridges\\Psr\\PsrToTracyLoggerAdapter","callType":"->","function":"log","memory_peak_usage":"10 MB","process_id":2891}
[2023-01-10T03:32:03.496218+01:00] default.ERROR: Code 2002: An exception occurred in the driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution in /__app__/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:103 [] {"url":"/admin/sign/in?backlink=4nqnp","ip":"172.18.0.1","http_method":"POST","server":"localhost","referrer":"http://localhost:1234/admin/sign/in?backlink=4nqnp","file":"/__app__/vendor/tracy/tracy/src/Bridges/Psr/PsrToTracyLoggerAdapter.php","line":57,"class":"Tracy\\Bridges\\Psr\\PsrToTracyLoggerAdapter","callType":"->","function":"log","memory_peak_usage":"10 MB","process_id":2892}
[2023-01-10T03:32:03.496608+01:00] default.ERROR: Doctrine\DBAL\Exception\ConnectionException: An exception occurred in the driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution #2002 in /__app__/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:103 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 2002): An exception occurred in the driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /__app__/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:103)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /__app__/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:30)\n[previous exception] [object] (PDOException(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /__app__/vendor/doctrine/dbal/src/Driver/PDO/MySQL/Driver.php:28)\n[previous exception] [object] (PDOException(code: 0): PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /__app__/vendor/doctrine/dbal/src/Driver/PDO/MySQL/Driver.php:28)"} {"url":"/admin/sign/in?backlink=4nqnp","ip":"172.18.0.1","http_method":"POST","server":"localhost","referrer":"http://localhost:1234/admin/sign/in?backlink=4nqnp","file":"/__app__/vendor/tracy/tracy/src/Bridges/Psr/PsrToTracyLoggerAdapter.php","line":57,"class":"Tracy\\Bridges\\Psr\\PsrToTracyLoggerAdapter","callType":"->","function":"log","memory_peak_usage":"10 MB","process_id":2892}
[2023-01-10T03:34:36.872156+01:00] default.ERROR: Code 2002: An exception occurred in the driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution in /__app__/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:103 [] {"url":"/admin/sign/in?backlink=4nqnp","ip":"172.18.0.1","http_method":"POST","server":"localhost","referrer":"http://localhost:1234/admin/sign/in?backlink=4nqnp","file":"/__app__/vendor/tracy/tracy/src/Bridges/Psr/PsrToTracyLoggerAdapter.php","line":57,"class":"Tracy\\Bridges\\Psr\\PsrToTracyLoggerAdapter","callType":"->","function":"log","memory_peak_usage":"4 MB","process_id":2893}
[2023-01-10T03:34:36.872612+01:00] default.ERROR: Doctrine\DBAL\Exception\ConnectionException: An exception occurred in the driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution #2002 in /__app__/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:103 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 2002): An exception occurred in the driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /__app__/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:103)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /__app__/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:30)\n[previous exception] [object] (PDOException(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /__app__/vendor/doctrine/dbal/src/Driver/PDO/MySQL/Driver.php:28)\n[previous exception] [object] (PDOException(code: 0): PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /__app__/vendor/doctrine/dbal/src/Driver/PDO/MySQL/Driver.php:28)"} {"url":"/admin/sign/in?backlink=4nqnp","ip":"172.18.0.1","http_method":"POST","server":"localhost","referrer":"http://localhost:1234/admin/sign/in?backlink=4nqnp","file":"/__app__/vendor/tracy/tracy/src/Bridges/Psr/PsrToTracyLoggerAdapter.php","line":57,"class":"Tracy\\Bridges\\Psr\\PsrToTracyLoggerAdapter","callType":"->","function":"log","memory_peak_usage":"4 MB","process_id":2893}
[2023-01-10T03:35:38.333091+01:00] default.ERROR: Code 2002: An exception occurred in the driver: SQLSTATE[HY000] [2002] Connection timed out in /__app__/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:103 [] {"url":"/admin/sign/in?backlink=4nqnp","ip":"172.18.0.1","http_method":"POST","server":"localhost","referrer":"http://localhost:1234/admin/sign/in?backlink=4nqnp","file":"/__app__/vendor/tracy/tracy/src/Bridges/Psr/PsrToTracyLoggerAdapter.php","line":57,"class":"Tracy\\Bridges\\Psr\\PsrToTracyLoggerAdapter","callType":"->","function":"log","memory_peak_usage":"10 MB","process_id":2887}
[2023-01-10T03:35:38.333395+01:00] default.ERROR: Doctrine\DBAL\Exception\ConnectionException: An exception occurred in the driver: SQLSTATE[HY000] [2002] Connection timed out #2002 in /__app__/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:103 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 2002): An exception occurred in the driver: SQLSTATE[HY000] [2002] Connection timed out at /__app__/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:103)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 2002): SQLSTATE[HY000] [2002] Connection timed out at /__app__/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:30)\n[previous exception] [object] (PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection timed out at /__app__/vendor/doctrine/dbal/src/Driver/PDO/MySQL/Driver.php:28)"} {"url":"/admin/sign/in?backlink=4nqnp","ip":"172.18.0.1","http_method":"POST","server":"localhost","referrer":"http://localhost:1234/admin/sign/in?backlink=4nqnp","file":"/__app__/vendor/tracy/tracy/src/Bridges/Psr/PsrToTracyLoggerAdapter.php","line":57,"class":"Tracy\\Bridges\\Psr\\PsrToTracyLoggerAdapter","callType":"->","function":"log","memory_peak_usage":"10 MB","process_id":2887}
[2023-01-10T03:36:55.485068+01:00] default.ERROR: Code 1054: An exception occurred while executing a query: SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.username' in 'field list' in /__app__/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:69 [] {"url":"/admin/sign/in?backlink=4nqnp","ip":"172.18.0.1","http_method":"POST","server":"localhost","referrer":"http://localhost:1234/admin/sign/in?backlink=4nqnp","file":"/__app__/vendor/tracy/tracy/src/Bridges/Psr/PsrToTracyLoggerAdapter.php","line":57,"class":"Tracy\\Bridges\\Psr\\PsrToTracyLoggerAdapter","callType":"->","function":"log","memory_peak_usage":"10 MB","process_id":2888}
[2023-01-10T03:36:55.485365+01:00] default.ERROR: Doctrine\DBAL\Exception\InvalidFieldNameException: An exception occurred while executing a query: SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.username' in 'field list' #1054 in /__app__/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:69 {"exception":"[object] (Doctrine\\DBAL\\Exception\\InvalidFieldNameException(code: 1054): An exception occurred while executing a query: SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.username' in 'field list' at /__app__/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:69)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1054): SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.username' in 'field list' at /__app__/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:30)\n[previous exception] [object] (PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.username' in 'field list' at /__app__/vendor/doctrine/dbal/src/Driver/PDO/Statement.php:101)"} {"url":"/admin/sign/in?backlink=4nqnp","ip":"172.18.0.1","http_method":"POST","server":"localhost","referrer":"http://localhost:1234/admin/sign/in?backlink=4nqnp","file":"/__app__/vendor/tracy/tracy/src/Bridges/Psr/PsrToTracyLoggerAdapter.php","line":57,"class":"Tracy\\Bridges\\Psr\\PsrToTracyLoggerAdapter","callType":"->","function":"log","memory_peak_usage":"10 MB","process_id":2888}
[2023-01-10T03:40:58.763132+01:00] default.ERROR: Code 1054: An exception occurred while executing a query: SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.username' in 'field list' in /__app__/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:69 [] {"url":"/admin/sign/in?backlink=4nqnp","ip":"172.18.0.1","http_method":"POST","server":"localhost","referrer":"http://localhost:1234/admin/sign/in?backlink=4nqnp","file":"/__app__/vendor/tracy/tracy/src/Bridges/Psr/PsrToTracyLoggerAdapter.php","line":57,"class":"Tracy\\Bridges\\Psr\\PsrToTracyLoggerAdapter","callType":"->","function":"log","memory_peak_usage":"6 MB","process_id":2891}
[2023-01-10T03:40:58.763487+01:00] default.ERROR: Doctrine\DBAL\Exception\InvalidFieldNameException: An exception occurred while executing a query: SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.username' in 'field list' #1054 in /__app__/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:69 {"exception":"[object] (Doctrine\\DBAL\\Exception\\InvalidFieldNameException(code: 1054): An exception occurred while executing a query: SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.username' in 'field list' at /__app__/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:69)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1054): SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.username' in 'field list' at /__app__/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:30)\n[previous exception] [object] (PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.username' in 'field list' at /__app__/vendor/doctrine/dbal/src/Driver/PDO/Statement.php:101)"} {"url":"/admin/sign/in?backlink=4nqnp","ip":"172.18.0.1","http_method":"POST","server":"localhost","referrer":"http://localhost:1234/admin/sign/in?backlink=4nqnp","file":"/__app__/vendor/tracy/tracy/src/Bridges/Psr/PsrToTracyLoggerAdapter.php","line":57,"class":"Tracy\\Bridges\\Psr\\PsrToTracyLoggerAdapter","callType":"->","function":"log","memory_peak_usage":"6 MB","process_id":2891}
[2023-01-10T03:44:10.190288+01:00] default.ERROR: Code 0: Property App\Model\Database\Entity\User::$username does not exist in /__app__/vendor/doctrine/persistence/src/Persistence/Mapping/RuntimeReflectionService.php:89 [] {"url":"/admin/sign/in?backlink=4nqnp","ip":"172.18.0.1","http_method":"POST","server":"localhost","referrer":"http://localhost:1234/admin/sign/in?backlink=4nqnp","file":"/__app__/vendor/tracy/tracy/src/Bridges/Psr/PsrToTracyLoggerAdapter.php","line":57,"class":"Tracy\\Bridges\\Psr\\PsrToTracyLoggerAdapter","callType":"->","function":"log","memory_peak_usage":"4 MB","process_id":2894}
[2023-01-10T03:44:10.190668+01:00] default.ERROR: ReflectionException: Property App\Model\Database\Entity\User::$username does not exist in /__app__/vendor/doctrine/persistence/src/Persistence/Mapping/RuntimeReflectionService.php:89 {"exception":"[object] (ReflectionException(code: 0): Property App\\Model\\Database\\Entity\\User::$username does not exist at /__app__/vendor/doctrine/persistence/src/Persistence/Mapping/RuntimeReflectionService.php:89)"} {"url":"/admin/sign/in?backlink=4nqnp","ip":"172.18.0.1","http_method":"POST","server":"localhost","referrer":"http://localhost:1234/admin/sign/in?backlink=4nqnp","file":"/__app__/vendor/tracy/tracy/src/Bridges/Psr/PsrToTracyLoggerAdapter.php","line":57,"class":"Tracy\\Bridges\\Psr\\PsrToTracyLoggerAdapter","callType":"->","function":"log","memory_peak_usage":"4 MB","process_id":2894}
[2023-01-10T03:46:29.407687+01:00] default.ERROR: Code 0: Call to undefined method App\Model\Database\Entity\User::isActivated() in /__app__/app/model/Security/Authenticator/UserAuthenticator.php:38 [] {"url":"/admin/sign/in?backlink=4nqnp","ip":"172.18.0.1","http_method":"POST","server":"localhost","referrer":"http://localhost:1234/admin/sign/in?backlink=4nqnp","file":"/__app__/vendor/tracy/tracy/src/Bridges/Psr/PsrToTracyLoggerAdapter.php","line":57,"class":"Tracy\\Bridges\\Psr\\PsrToTracyLoggerAdapter","callType":"->","function":"log","memory_peak_usage":"10 MB","process_id":2889}
[2023-01-10T03:46:29.408292+01:00] default.ERROR: Error: Call to undefined method App\Model\Database\Entity\User::isActivated() in /__app__/app/model/Security/Authenticator/UserAuthenticator.php:38 {"exception":"[object] (Error(code: 0): Call to undefined method App\\Model\\Database\\Entity\\User::isActivated() at /__app__/app/model/Security/Authenticator/UserAuthenticator.php:38)"} {"url":"/admin/sign/in?backlink=4nqnp","ip":"172.18.0.1","http_method":"POST","server":"localhost","referrer":"http://localhost:1234/admin/sign/in?backlink=4nqnp","file":"/__app__/vendor/tracy/tracy/src/Bridges/Psr/PsrToTracyLoggerAdapter.php","line":57,"class":"Tracy\\Bridges\\Psr\\PsrToTracyLoggerAdapter","callType":"->","function":"log","memory_peak_usage":"10 MB","process_id":2889}
